apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: capstone
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: tasktracker
  # Connection string for API
  DB_HOST: postgres-service
