apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
  namespace: capstone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role
  namespace: capstone
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: capstone
subjects:
- kind: ServiceAccount
  name: readonly-sa
  namespace: capstone
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
